### PR TITLE
Continuous integration using AppVeyor

### PR DESCRIPTION
**Pull request by springcomp**
To automate the packing and releasing of new versions, I propose to setup [continuous integration](https://ci.appveyor.com/project/springcomp/optimized-azerty-win) using AppVeyor.

For this to work on this repository, the secure GitHub authorization token used near the bottom of the `appveyor.yml` file needs to be updated to one coming from this repository. Also, the status badge in the `README.md` file must reflect the AppVeyor project associated with this repository.

For this PR, I have setup a project myself.
If you would prefer to host the AppVeyor project, you need to create your own AppVeyor project and the two modifications above must be carried out. Or I can host the AppVeyor project but, in order to push releases to this repository, the secure authorization token from this repository must be specified in the file, instead of mine.

### CODE REVIEW

**Comment by tbolon** [comment]
It seems the binaries are included in the source (msi). Is it expected?

**Comment by springcomp** [comment]
The `msi` files are bootstrapped files that never change based on the name and metadata of the layout. The actual DLL is built dynamically and is put in a folder based upon the target CPU architecture. Therefore, there is no harm in putting those files in the source code.

Building the layout DLLs with MSKLC does not work in an unattended fashion so I has to rely on using the underlying `kbdutool.exe` program.

In fact, the benefit of using the low-level `kbdutool.exe` instead of the high-level `msklc.exe` tool to build the layout DLLs is that MSKLC is limited whereas the `kbdutool.exe` supports chained dead-keys that I intend to make use of to implement missing extended characters.

**Comment by springcomp** [comment]
I’m using the procedure outlined here:
http://accentuez.mon.nom.free.fr/Clavier-CreationClavier.php

**Comment by tbolon** [comment]
I just created a similar branch here with all your changes included, then edited the files as recommended.

Perhaps you could update your PR with the new values from my branch, so I could merge your PR as-is? I will then delete my local branch.

I did not review the method you set up to decide when to deploy in the release tab. Something seems to be related to the tagging of the sources, but I did not read the documentation yet.

**Comment by springcomp** [comment]
Thank you very much.

To be clear there is a continuous build for each build on the master branch. This is used to check the build.
When tagging the master branch with a version, then a build and a release are performed.

At the moment, this allows to create a release only when explicitly required by a human.

This is very configurable so please let me know what you would like.

**Pull request merged**
