### PR TITLE
New - Support subscript and superscript parentheses.

### PR DESCRIPTION
**Pull request by springcomp**
Via <kbd>^</kbd> and <kbd>AltGr</kbd>+<kbd>^</kbd>, allows to type such strings as:

- Hello⁽¹⁾ World₍₂₎.

### CODE REVIEW

**Comment by tbolon** [comment]
Sorry, but I did not see that this change was not a part of the official spec.

**Comment by tbolon** [comment]
If you want to discuss this change, please create a new PR, as this one is considered merged.

**Comment by springcomp** [comment]
Although this is not strictly part of the standard, I believe there is no harm done to add characters to positions that are not otherwize assigned any meaning by the standard. Since subscript and superscript characters are supported, I figured we could also support other simple math signs.

I think this goes in the spirit to the standard that already includes many variants of math comparison signs (which arguably do not fall into the responsabilities of a French layout).

Along those lines. I also have other PRs ready to include the `+`. `- ` and  `=` subscript and superscript signs that I would propose if this one goes through.

**Comment by tbolon** [comment]
You can submit the PR again if you want, I will merge it.

**Pull request merged**
